version: 2
jobs:
  alpine3:
    docker:
      - image: dshearer/jobber-cci-alpine:2

    working_directory: /home/builder/jobber

    steps:
      - checkout
      - run: mkdir pkgs
      - run: make -C packaging/alpine_3.6 pkg-local DESTDIR="$PWD/pkgs"
      - store_artifacts:
          path: pkgs
          destination: alpine3

workflows:
  version: 2
  build-packages:
    jobs:
      - alpine3
